// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJSpz2gEC-Nb5XSen_gmcUqHf98FAHDMs',
    appId: '1:701408386601:web:4e60062d940bfc8ce2c638',
    messagingSenderId: '701408386601',
    projectId: 'cryptolistapp-2ac6c',
    authDomain: 'cryptolistapp-2ac6c.firebaseapp.com',
    storageBucket: 'cryptolistapp-2ac6c.appspot.com',
    measurementId: 'G-0Y26N944JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjhX1kk06aiHFd9KGR0-TrrTqMTdiGcFA',
    appId: '1:701408386601:android:dedbb8a006c94893e2c638',
    messagingSenderId: '701408386601',
    projectId: 'cryptolistapp-2ac6c',
    storageBucket: 'cryptolistapp-2ac6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzgrMaG60MICBUpzosuiWvkV86BZxxzqk',
    appId: '1:701408386601:ios:5607d8b34e3397afe2c638',
    messagingSenderId: '701408386601',
    projectId: 'cryptolistapp-2ac6c',
    storageBucket: 'cryptolistapp-2ac6c.appspot.com',
    iosBundleId: 'com.example.cryptoCurrencies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzgrMaG60MICBUpzosuiWvkV86BZxxzqk',
    appId: '1:701408386601:ios:593bf75d9a33280de2c638',
    messagingSenderId: '701408386601',
    projectId: 'cryptolistapp-2ac6c',
    storageBucket: 'cryptolistapp-2ac6c.appspot.com',
    iosBundleId: 'com.example.cryptoCurrencies.RunnerTests',
  );
}
